### ISSUE TITLE
Push version that works on Windows to Hackage

### ISSUE THREAD

**Issue by sol** [haskell-compat/base-orphans#10]

**Comment by sol** [comment]
@RyanGlScott the version we have on Hackage still does not build on Windows right?  Can we do a release some time soon so fix this.  It's kind of urgent as `errorcall-eq-instance` depends on `base-orphans` which in turn is already is in use by some people.

**Comment by RyanGlScott** [comment]
I'm working on a pull request that should fix #7 tonight, so we can bundle that with the new release.

**Comment by sol** [comment]
From my perspective it's still most important to have something that compiles cross-platform on Hackage as soon as possible.

**Comment by RyanGlScott** [comment]
This should be fixed as of `base-orphans-0.2.0`.

**Comment by sol** [comment]
:)
