### ISSUE TITLE
0.4.2 fails to build for me with 7.10.2

### ISSUE THREAD

**Issue by jwiegley** [haskell-compat/base-orphans#28]
I get the following:

```
Building base-orphans-0.4.2...
Preprocessing library base-orphans-0.4.2...
[1 of 1] Compiling Data.Orphans     ( src/Data/Orphans.hs, dist/build/Data/Orphans.o )
In-place registering base-orphans-0.4.2...
Preprocessing test suite 'spec' for base-orphans-0.4.2...
[ 1 of 11] Compiling System.Posix.Types.OrphansSpec ( test/System/Posix/Types/OrphansSpec.hs, dist/build/spec/spec-tmp/System/Posix/Types/OrphansSpec.dyn_o )

test/System/Posix/Types/OrphansSpec.hs:19:13:
    Not in scope: type constructor or class ‘Int32’
builder for ‘/nix/store/8s0vn49w3x25f7xp0g06vi4fr3fa9lw0-haskell-base-orphans-0.4.2.drv’ failed with exit code 1
```

**Comment by RyanGlScott** [comment]
I'll fix this tonight.

Out of curiosity, what computer architecture and OS are you using?

**Comment by jwiegley** [comment]
This is on "OS X" using Nix.

**Comment by RyanGlScott** [comment]
OK, I think my latest commits fix this issue. Since I don't have access to OS X, can you try building it to make sure it works?

**Comment by aycanirican** [comment]
@RyanGlScott Sorry it's still broken. I just tried 267163f413d4e59f40b9c8930a05ff757a5db974.

```
\[\][nix-shell:/private/tmp/base-orphans]$\[\] runhaskell Setup.hs build
Building base-orphans-0.4.2...
Preprocessing library base-orphans-0.4.2...
In-place registering base-orphans-0.4.2...
Preprocessing test suite 'spec' for base-orphans-0.4.2...
[10 of 11] Compiling System.Posix.Types.OrphansSpec ( test/System/Posix/Types/OrphansSpec.hs, dist/build/spec/spec-tmp/System/Posix/Types/OrphansSpec.o )

test/System/Posix/Types/OrphansSpec.hs:19:13:
    Not in scope: type constructor or class ‘Int32’
```

**Comment by dmjio** [comment]
I'm getting the same, can't rebuild.

**Comment by dmjio** [comment]
`import GHC.Int` fixes it for me...

**Comment by RyanGlScott** [comment]
Oops, I didn't apply the same diligence to fixing the test suite. Is it working now?

**Comment by dmjio** [comment]
@RyanGlScott that works for me! 
```haskell
Finished in 0.0157 seconds
49 examples, 0 failures
```

**Comment by RyanGlScott** [comment]
Hooray! Uploaded to Hackage as [`base-orphans-0.4.3`](http://hackage.haskell.org/package/base-orphans-0.4.3).

**Comment by aycanirican** [comment]
Thanks @RyanGlScott.

**Comment by PiotrJustyna** [comment]
:+1: @RyanGlScott

**Comment by dmjio** [comment]
Thank you !

On Tue, Aug 11, 2015 at 3:02 AM, Piotr Justyna <notifications@github.com>
wrote:

> [image: :+1:] @RyanGlScott <https://github.com/RyanGlScott>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haskell-compat/base-orphans/issues/28#issuecomment-129751050>
> .
>



-- 
Cell: 1.630.740.8204
