### ISSUE TITLE
`base-orphans-0.4.*` fails to install on Windows

### ISSUE THREAD

**Issue by Gabriel439** [haskell-compat/base-orphans#29]
The error I get is:

```
src\Data\Orphans.hs:455:29
    Not in scope: type constructor or class `Console.Handler`
```

**Comment by RyanGlScott** [comment]
Which version of `base-orphans` and GHC are you using?

**Comment by Gabriel439** [comment]
`base-orphans-0.4.0` and `ghc-7.6.3`

**Comment by RyanGlScott** [comment]
This is a known issue with`base-orphans-0.4.0` (see #26), which should be fixed as of `0.4.1`.

**Comment by Gabriel439** [comment]
I think you might be able to blacklist `base-orphans-0.4.0` so that it is not selected by build plans.  See here:

* http://stackoverflow.com/questions/21724729/blacklisting-your-own-faulty-hackage-release

**Comment by RyanGlScott** [comment]
Sorry about that, it should be blacklisted now. (I've always used the latest versions of things on Hackage, so it never occurred to me before to blacklist nonworking versions.)

**Comment by Gabriel439** [comment]
No problem!  It's actually not strictly necessary to blacklist bad packages, but in this case `lens` had a dependency on `base-orphans` of `0.3` to `(< 0.5)` and without the blacklist this would have complicated the `lens` dependencies a lot more

**Comment by RyanGlScott** [comment]
I'll go ahead and close this now that the Hackage issues and #28 appear to be resolved.
