### ISSUE TITLE
Multiple modules

### ISSUE THREAD

**Issue by ekmett** [haskell-compat/base-orphans#3]
One issue with the multi-module orphan structure here is that while it provides a code organizational structure, the user can't 'view source' in the haddocks and see what they are getting themselves in for.

It requires a user to `cabal unpack` and dig by hand.

**Comment by sol** [comment]
I would be fine with having all the orphans defined directly in `Data.Orphans`.  But I'm not that opinionated here.

**Comment by RyanGlScott** [comment]
That works for me. Our original approach was to tell users what orphan instances were defined in the README, but sometines, nothing beats looking at the source directly.

**Comment by RyanGlScott** [comment]
Fixed in 9302c8a1c6c39399cee868ec722f4e60e2aaf100.
