### ISSUE TITLE
GHC.IP is gone in GHC HEAD

### ISSUE THREAD

**Issue by ekmett** [haskell-compat/base-orphans#30]
This precludes base-orphans from building on GHC 7.11, and prevents me from testing basically my entire package hierarchy.

**Comment by RyanGlScott** [comment]
Whoops, sorry for not testing against HEAD previously—I'll get a new version on Hackage soon.

**Comment by RyanGlScott** [comment]
Uploaded to Hackage as `base-orphans-0.4.4`. The upper version bounds of `base-orphans-0.4.3` were also changed so that it can't be built with `base-4.8.2.0`.
