### ISSUE TITLE
instance Storable Complex is stricter than in storable-complex

### ISSUE THREAD

**Issue by amigalemming** [haskell-compat/base-orphans#36]
When I recently recompiled a program it stopped with a nasty `Prelude.undefined`.
Fortunately I remembered that I just fiddled around with `storable-complex` and its new patch that moves to `base-orphans`. This I found the culprit quickly: In `base-orphans` you pattern match on (:+). Instead you should either use a lazy pattern match:
~~~~
sizeOf ~(a :+ _) = 2 * sizeOf a
~~~~
or use a field accessor:
~~~~
sizeOf a = 2 * sizeOf (realPart a)
~~~~
The instance in `base` uses the second way.

**Comment by RyanGlScott** [comment]
Sorry about that - the slighly modified `Storable` instance for `Complex` was a relic from an older version of `base-orphans` which tried to avoid using `-XScopedTypeVariables`.  But given that this version is too strict, I've modified it to do things _exactly_ how `base` handles its `Storable Complex` and `Storable Ratio` instances.

Once the build is done validating, I'll post a new version to Hackage.
