### ISSUE TITLE
add Show instance for functions, dropped in GHC 8

### ISSUE THREAD

**Issue by simonmichael** [haskell-compat/base-orphans#38]
I believe until GHC 8's base 4.9, Text.Show.Function provided a Show instance for a -> b. Should this be added to base-orphans ?

**Comment by RyanGlScott** [comment]
It was removed?

```
$ /opt/ghc/8.0.1/bin/ghci                                                                 
GHCi, version 8.0.0.20160421: http://www.haskell.org/ghc/  :? for help                    
Loaded GHCi configuration from /home/ryanglscott/.ghci                                    
λ> import Text.Show.Functions 
λ> show (+1)
"<function>"
```

**Comment by simonmichael** [comment]
Ah.. it's simply not provided by Prelude any more, you have to import Text.Show.Functions explicitly.

**Comment by RyanGlScott** [comment]
To be accurate, `Prelude` has never exported a `Show` instance for `(a -> b)`. You have to explicitly import `Text.Show.Functions` to use it.

**Comment by simonmichael** [comment]
Ok.. I didn't need that import with GHC 7, I guess it was being reexported by something else I had imported.

**Comment by simonmichael** [comment]
It was Text.Regex.TDFA. So I guess there's no issue here. Thanks.
