### ISSUE TITLE
Test suite failure with GHC 8.2.1-rc3

### ISSUE THREAD

**Issue by peti** [haskell-compat/base-orphans#42]
The test suite fails, saying:

~~~
  test/Data/Version/OrphansSpec.hs:20: 
  1) Data.Version.Orphans, Data Version instance, allows obtaining a Version constructor
       expected: "Data.Version.Version"
        but got: "Version"
~~~

**Comment by RyanGlScott** [comment]
Which version of `base-orphans` are you testing? The tests for [`base-orphans-0.6`](http://hackage.haskell.org/package/base-orphans-0.6) currently pass with GHC 8.2.

**Comment by peti** [comment]
I was using `base-orphans-0.5.4` from LTS Haskell 8.x. I'll give the newer version a shot.

**Comment by peti** [comment]
OK, the new version works fine! Thank you for the quick response.
