### ISSUE TITLE
Push to Hackage

### ISSUE THREAD

**Issue by sol** [haskell-compat/base-orphans#5]

**Comment by sol** [comment]
@RyanGlScott Anything we still need to do before we can push this to Hackage?

**Comment by RyanGlScott** [comment]
It has everything that `base-compat` has at the moment, so it should be sufficient. I noticed that some really old versions of `base` are missing some `Applicative` instances (I can't remember which modules off the top of my head), but we can get those later.

**Comment by sol** [comment]
Pushed to Hackage.
