### ISSUE TITLE
Solo instances

### ISSUE THREAD

**Issue by phadej** [haskell-compat/base-orphans#58]
• No instance for (Eq (Solo Char)) arising from a use of ‘hasEq’
  • No instance for (Ord (Solo Char)) arising from a use of ‘hasOrd’
    • No instance for (Bounded (Solo Char))
    • No instance for (Enum (Solo Char))
    • No instance for (Ix (Solo Char)) arising from a use of ‘hasIx’

I'm not sure what would be best plan. Forget about `base-4.15` at this point and just add these instances to `base-orphans`?
OTOH, GHC-9.0.1 is so broken, so maybe it's worth adding these instances to `base-4.15.1.0`, yet it's some extra work...

I'll let you decide

cc @treeowl

**Comment by treeowl** [comment]
I added a slew of instances a while back. Did I somehow miss `Eq` and `Ord`??? I'm not sure we want/need `Enum` and `Ix` instances.

**Comment by phadej** [comment]
@treeowl true, Looks like `Eq` and `Ord` are missing from `master` too (i.e. GHC-9.2)

`OneTuple` had `Ix`, `Enum` and `Bounded`. Based on the fact that there's only one reasonable instance for these, I don't see a reason to not define them, even they are somewhat useless.

**Comment by treeowl** [comment]
Darn. You want to open the MR, or should I do it later?

**Comment by phadej** [comment]
@treeowl I'll leave some fun for you, be my guest :)

**Comment by RyanGlScott** [comment]
See #59.

**Comment by RyanGlScott** [comment]
I've uploaded [`base-orphans-0.8.6`](https://hackage.haskell.org/package/base-orphans-0.8.6) to Hackage with these changes.
