### ISSUE TITLE
Fix Windows/GHCJS build

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-compat/base-orphans#6]
I inadvertently prevented `base-orphans` from building on Windows (and GHCJS) by importing `GHC.Event`, which isn't present on those platforms. I should also derive `Typeable` instances for data types in `GHC.Conc.Windows`, which is _only_ present on Windows.

**Comment by sol** [comment]
Ryan, I added you to the maintainer groups of base-compat and base-orphans on Hackage, in case you want to upload a new version.
