### ISSUE TITLE
Eq/Ord (Generically1 f a)

### ISSUE THREAD

**Issue by phadej** [haskell-compat/base-orphans#63]
(to be) Added in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4727

**Comment by RyanGlScott** [comment]
Good point. We should add these instances to the `generically` compatibility package as well.

**Comment by phadej** [comment]
@RyanGlScott yes, and then `generically` should depends on `base-orphans` to always have the instances available.

Let's wait when the instances are actually added and released. They could be already added in base-4.17.1.0 for example.

**Comment by RyanGlScott** [comment]
These were first introduced in `base-4.18.*`, which is bundled with GHC 9.6. I've opened #64 to track all of these instances, and I plan to submit a patch that adds them all in one go. I'll close this issue in favor of #64.

I have also opened haskell-compat/generically#2 for backporting the same instances to `generically`.
